language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"
before_install:
  - pip install --upgrade pip
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install --upgrade pytest
install: pip install .
script: pytest
